name: ci

on:
  - push

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - run: pnpm install

  lint:
    runs-on: ubuntu-latest

    needs: install_dependencies

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm lint

  check_types:
    runs-on: ubuntu-latest

    needs: install_dependencies

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm check
